### ISSUE TITLE
$(...).jScroll is not a function

### ISSUE THREAD

**Issue by yahilmadakiya** [wduffy/jScroll#19]
console error  `Uncaught TypeError: $(...).jScroll is not a function`

checking here :point_right: http://www.wduffy.co.uk/jScroll
![jscroll-console-eooro](https://cloud.githubusercontent.com/assets/11607839/22583265/797f0bae-ea11-11e6-96b3-2847dbf5b38c.png)

**Comment by smoleniuch** [comment]
method names are case sensitive,you should try instead .jscroll()
